import { utilService } from './util.service.js'

export const boardMembers = [
    { id: 'ea', name: 'Eden Avgi', initials: 'EA', color: '#1f845a' },
    { id: 'ga', name: 'Golan Asraf', initials: 'GA', color: '#0c66e4' },
    { id: 'll', name: 'Lior Lazar', initials: 'LL', color: '#1d7afc' },
    { id: 'r', name: 'Reut Ery', initials: 'R', color: '#8270db' },
    { id: 'dm', name: 'Dana M.', initials: 'DM', color: '#c9372c' },
]

export const labelPalette = {
    // Row 1 - Light colors
    'green-light': { color: '#4bce97', name: '' },
    'yellow-light': { color: '#f5cd47', name: '' },
    'orange-light': { color: '#fea362', name: '' },
    'red-light': { color: '#f87168', name: '' },
    'purple-light': { color: '#9f8fef', name: '' },

    // Row 2 - Medium colors
    'green': { color: '#1f845a', name: '' },
    'yellow': { color: '#946f00', name: '' },
    'orange': { color: '#c25100', name: '' },
    'red': { color: '#ca3521', name: '' },
    'purple': { color: '#6e5dc6', name: '' },

    // Row 3 - Dark colors
    'green-dark': { color: '#164b35', name: '' },
    'yellow-dark': { color: '#7f5f01', name: '' },
    'orange-dark': { color: '#a54800', name: '' },
    'red-dark': { color: '#ae2a19', name: '' },
    'purple-dark': { color: '#5e4db2', name: '' },

    // Row 4 - Light pastels
    'blue-light': { color: '#579dff', name: '' },
    'sky-light': { color: '#6cc3e0', name: '' },
    'lime-light': { color: '#94c748', name: '' },
    'pink-light': { color: '#e774bb', name: '' },
    'gray-light': { color: '#8590a2', name: '' },

    // Row 5 - Medium blues and greens
    'blue': { color: '#0c66e4', name: '' },
    'sky': { color: '#227d9b', name: '' },
    'lime': { color: '#5b7f24', name: '' },
    'pink': { color: '#ae4787', name: '' },
    'gray': { color: '#626f86', name: '' },

    // Row 6 - Dark blues and greens
    'blue-dark': { color: '#09326c', name: '' },
    'sky-dark': { color: '#206a83', name: '' },
    'lime-dark': { color: '#4c6b1f', name: '' },
    'pink-dark': { color: '#943d73', name: '' },
    'gray-dark': { color: '#44546f', name: '' },
}

// ==================== FULL DEMO BOARDS ARRAY ==================== //
export const demoBoards = [
    // ===== BOARD #1: Team Collaboration Board (exactly as sent) =====
    {
        _id: utilService.makeId(),
        title: 'Team Collaboration Board',
        isStarred: true,
        createdAt: Date.now(),
        createdBy: {
            _id: 'u101',
            fullname: 'Eden Avgi',
            imgUrl: 'https://i.pravatar.cc/150?img=3',
        },
        style: {
            backgroundColor: '#7a8287',
            backgroundImage:
                'url(https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1500&q=80)',
        },
        labels: [
            { id: 'l101', title: 'Design', color: '#0079bf' },
            { id: 'l102', title: 'Backend', color: '#00c2e0' },
            { id: 'l103', title: 'Frontend', color: '#ff9f1a' },
            { id: 'l104', title: 'QA', color: '#eb5a46' },
            { id: 'l105', title: 'Research', color: '#c377e0' },
            { id: 'l106', title: 'Priority', color: '#61bd4f' },
        ],
        members: [
            { _id: 'u101', fullname: 'Eden Avgi', imgUrl: 'https://i.pravatar.cc/150?img=3' },
            { _id: 'u102', fullname: 'Golan Asraf', imgUrl: 'https://i.pravatar.cc/150?img=5' },
            { _id: 'u103', fullname: 'Lior Lazer', imgUrl: 'https://i.pravatar.cc/150?img=7' },
            { _id: 'u104', fullname: 'Liran Tal', imgUrl: 'https://i.pravatar.cc/150?img=8' },
            { _id: 'u105', fullname: 'Shira Azulay', imgUrl: 'https://i.pravatar.cc/150?img=9' },
        ],
        lists: [
            {
                id: utilService.makeId(),
                title: 'Quick Tasks',
                style: { backgroundColor: '#bbc9ff' },
                tasks: [
                    { id: utilService.makeId(), title: 'Reply to client email' },
                    { id: utilService.makeId(), title: 'Fix layout padding on board header', style: { backgroundColor: '#ffb74d' } },
                    { id: utilService.makeId(), title: 'Rename CSS variables for clarity' },
                    { id: utilService.makeId(), title: 'Review pull request #24', style: { backgroundColor: '#a29bfe' } },
                ],
            },
            {
                id: utilService.makeId(),
                title: 'Research & Planning',
                style: { backgroundColor: '#ffeaa7' },
                tasks: [
                    { id: utilService.makeId(), title: 'Define MVP goals and priorities' },
                    { id: utilService.makeId(), title: 'Research drag-and-drop libraries for React', style: { backgroundColor: '#fab1a0' } },
                    { id: utilService.makeId(), title: 'Benchmark Trello’s performance with large boards' },
                    { id: utilService.makeId(), title: 'Document data flow between components', style: { backgroundColor: '#55efc4' } },
                    { id: utilService.makeId(), title: 'Prepare architecture diagram for final presentation' },
                    { id: utilService.makeId(), title: 'List user pain points found in interviews' },
                ],
            },
            {
                id: utilService.makeId(),
                title: 'Design Phase',
                tasks: [
                    { id: utilService.makeId(), title: 'Set up design system in Figma', style: { backgroundColor: '#74b9ff' } },
                    { id: utilService.makeId(), title: 'Redesign login screen – compact layout' },
                    { id: utilService.makeId(), title: 'Design interactive hover state for task cards', style: { backgroundColor: '#25ed4d' } },
                    { id: utilService.makeId(), title: 'Create reusable icon component' },
                    { id: utilService.makeId(), title: 'Define color tokens and spacing units', style: { backgroundColor: '#fdcb6e' } },
                    { id: utilService.makeId(), title: 'Test dark mode contrast on mobile' },
                    { id: utilService.makeId(), title: 'Export illustrations for landing page', style: { backgroundColor: '#fab1a0' } },
                    { id: utilService.makeId(), title: 'Prototype board scroll animation' },
                ],
            },
            {
                id: utilService.makeId(),
                title: 'Frontend Development',
                style: { backgroundColor: '#ff8a53' },
                tasks: [
                    { id: utilService.makeId(), title: 'Build <BoardDetails> layout and toolbar' },
                    { id: utilService.makeId(), title: 'Implement <TaskList> with task add and cancel behavior', style: { backgroundColor: '#ffeaa7' } },
                    { id: utilService.makeId(), title: 'Handle click outside to close add task form' },
                    { id: utilService.makeId(), title: 'Integrate utilService for id generation', style: { backgroundColor: '#fab1a0' } },
                    { id: utilService.makeId(), title: 'Add smooth transitions between board states' },
                    { id: utilService.makeId(), title: 'Implement keyboard shortcuts for adding lists' },
                    { id: utilService.makeId(), title: 'Create <TaskPreview> component with edit button' },
                    { id: utilService.makeId(), title: 'Refactor boardService for consistency' },
                    { id: utilService.makeId(), title: 'Optimize rerenders using React.memo', style: { backgroundColor: '#81ecec' } },
                    { id: utilService.makeId(), title: 'Fix scrollbar overflow in lists container' },
                ],
            },
            {
                id: utilService.makeId(),
                title: 'Backend & Storage',
                tasks: [
                    { id: utilService.makeId(), title: 'Implement boardService.query() with localStorage' },
                    { id: utilService.makeId(), title: 'Add createDemoBoard() on first app load', style: { backgroundColor: '#55efc4' } },
                    { id: utilService.makeId(), title: 'Ensure board.id persists after save' },
                    { id: utilService.makeId(), title: 'Set up Express server (future step)' },
                    { id: utilService.makeId(), title: 'Test async-storage post() and put() functions' },
                    { id: utilService.makeId(), title: 'Add filtering logic for board search' },
                    { id: utilService.makeId(), title: 'Handle board deletion properly', style: { backgroundColor: '#ff7675' } },
                ],
            },
            {
                id: utilService.makeId(),
                title: 'QA & Testing',
                style: { backgroundColor: '#cbb0e8' },
                tasks: [
                    { id: utilService.makeId(), title: 'Verify task addition and removal works', style: { backgroundColor: '#a3e635' } },
                    { id: utilService.makeId(), title: 'Test renaming lists and canceling empty titles' },
                    { id: utilService.makeId(), title: 'Check persistence after reload (localStorage)' },
                    { id: utilService.makeId(), title: 'Ensure board saves on every change' },
                    { id: utilService.makeId(), title: 'Validate hover effect on edit task button', style: { backgroundColor: '#74b9ff' } },
                    { id: utilService.makeId(), title: 'Run tests with multiple lists open simultaneously' },
                    { id: utilService.makeId(), title: 'Check performance with 100+ tasks' },
                ],
            },
            {
                id: utilService.makeId(),
                title: 'Deployment & Docs',
                tasks: [
                    { id: utilService.makeId(), title: 'Create GitHub repo and push project' },
                    { id: utilService.makeId(), title: 'Write detailed README with setup guide' },
                    { id: utilService.makeId(), title: 'Deploy on GitHub Pages', style: { backgroundColor: '#81ecec' } },
                    { id: utilService.makeId(), title: 'Test production build performance' },
                    { id: utilService.makeId(), title: 'Add preview screenshots and demo link' },
                    { id: utilService.makeId(), title: 'Plan backend integration phase' },
                ],
            },
        ],
    },

    // ===== BOARD #2: Thailand Adventure 2025 (exactly as sent) =====
    {
        _id: utilService.makeId(),
        title: 'Thailand Adventure 2025 🇹🇭',
        isStarred: true,
        createdAt: Date.now(),
        createdBy: {
            _id: 'u101',
            fullname: 'Eden Avgi',
            imgUrl: 'https://i.pravatar.cc/150?img=3',
        },
        style: {
            backgroundColor: '#f4b183',
            backgroundImage:
                'url(https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1500&q=80)',
        },
        labels: [
            { id: 'l101', title: 'Accommodation', color: '#00bcd4' },
            { id: 'l102', title: 'Transport', color: '#ffb74d' },
            { id: 'l103', title: 'Activities', color: '#81c784' },
            { id: 'l104', title: 'Food & Drinks', color: '#ff7043' },
            { id: 'l105', title: 'Culture', color: '#9575cd' },
            { id: 'l106', title: 'Essentials', color: '#e57373' },
        ],
        members: [
            { _id: 'u101', fullname: 'Eden Avgi', imgUrl: 'https://i.pravatar.cc/150?img=3' },
            { _id: 'u102', fullname: 'Golan Asraf', imgUrl: 'https://i.pravatar.cc/150?img=5' },
            { _id: 'u103', fullname: 'Lior Lazer', imgUrl: 'https://i.pravatar.cc/150?img=7' },
            { _id: 'u104', fullname: 'Liran Tal', imgUrl: 'https://i.pravatar.cc/150?img=8' },
            { _id: 'u105', fullname: 'Shira Azulay', imgUrl: 'https://i.pravatar.cc/150?img=9' },
        ],
        lists: [
            {
                id: utilService.makeId(),
                title: 'Before the Trip ',
                style: { backgroundColor: '#ffe0b2' },
                tasks: [
                    { id: utilService.makeId(), title: 'Book flights to Bangkok', style: { backgroundColor: '#ffb74d' } },
                    { id: utilService.makeId(), title: 'Apply for Thai eVisa' },
                    { id: utilService.makeId(), title: 'Buy travel insurance (includes diving coverage)' },
                    { id: utilService.makeId(), title: 'Check vaccination requirements', style: { backgroundColor: '#81c784' } },
                    { id: utilService.makeId(), title: 'Convert some cash to Thai Baht (THB)' },
                    { id: utilService.makeId(), title: 'Download offline maps and phrasebook app' },
                ],
            },
            {
                id: utilService.makeId(),
                title: 'Bangkok',
                style: { backgroundColor: '#f8bbd0' },
                tasks: [
                    { id: utilService.makeId(), title: 'Visit the Grand Palace & Wat Pho', style: { backgroundColor: '#9575cd' } },
                    { id: utilService.makeId(), title: 'Take a tuk-tuk ride through Chinatown' },
                    { id: utilService.makeId(), title: 'Rooftop dinner at Octave Sky Bar', style: { backgroundColor: '#ff7043' } },
                    { id: utilService.makeId(), title: 'Explore Chatuchak Weekend Market' },
                    { id: utilService.makeId(), title: 'Stay 3 nights at Siam@Siam Design Hotel', style: { backgroundColor: '#00bcd4' } },
                ],
            },
            {
                id: utilService.makeId(),
                title: 'Chiang Mai ',
                style: { backgroundColor: '#c8e6c9' },
                tasks: [
                    { id: utilService.makeId(), title: 'Fly Bangkok → Chiang Mai (AirAsia)' },
                    { id: utilService.makeId(), title: 'Elephant Nature Park full-day visit', style: { backgroundColor: '#81c784' } },
                    { id: utilService.makeId(), title: 'Explore old temples: Wat Chedi Luang, Wat Phra Singh' },
                    { id: utilService.makeId(), title: 'Book stay at Green Tiger House (eco-hotel)', style: { backgroundColor: '#00bcd4' } },
                    { id: utilService.makeId(), title: 'Take a Thai cooking class with locals' },
                    { id: utilService.makeId(), title: 'Night Bazaar & Sunday Walking Street Market', style: { backgroundColor: '#ff7043' } },
                ],
            },
            {
                id: utilService.makeId(),
                title: 'Koh Phangan ',
                style: { backgroundColor: '#b3e5fc' },
                tasks: [
                    { id: utilService.makeId(), title: 'Ferry from Surat Thani to Koh Phangan', style: { backgroundColor: '#ffb74d' } },
                    { id: utilService.makeId(), title: 'Book bungalow at Sunset Hill Resort' },
                    { id: utilService.makeId(), title: 'Attend Full Moon Party (Haad Rin Beach)' },
                    { id: utilService.makeId(), title: 'Take snorkeling trip to Koh Ma reef', style: { backgroundColor: '#81c784' } },
                    { id: utilService.makeId(), title: 'Yoga & meditation session at The Sanctuary' },
                    { id: utilService.makeId(), title: 'Rent a scooter for island exploration', style: { backgroundColor: '#ff7043' } },
                ],
            },
            {
                id: utilService.makeId(),
                title: 'Krabi & Islands ',
                style: { backgroundColor: '#fff59d' },
                tasks: [
                    { id: utilService.makeId(), title: 'Stay 3 nights in Ao Nang Cliff Resort', style: { backgroundColor: '#00bcd4' } },
                    { id: utilService.makeId(), title: '4 Islands boat tour: Phra Nang, Tup, Chicken, Poda' },
                    { id: utilService.makeId(), title: 'Kayak through mangroves at Ao Thalane', style: { backgroundColor: '#81c784' } },
                    { id: utilService.makeId(), title: 'Dinner at The Hilltop overlooking the bay' },
                    { id: utilService.makeId(), title: 'Rock climbing at Railay Beach' },
                    { id: utilService.makeId(), title: 'Massage & spa evening before flight' },
                ],
            },
            {
                id: utilService.makeId(),
                title: 'Packing List ',
                style: { backgroundColor: '#d1c4e9' },
                tasks: [
                    { id: utilService.makeId(), title: 'Passport & printed eVisa', style: { backgroundColor: '#e57373' } },
                    { id: utilService.makeId(), title: 'Light cotton clothes + flip-flops' },
                    { id: utilService.makeId(), title: 'Mosquito repellent & sunscreen SPF 50', style: { backgroundColor: '#ffb74d' } },
                    { id: utilService.makeId(), title: 'GoPro + waterproof case' },
                    { id: utilService.makeId(), title: 'Travel adapter (Type A/B/C)', style: { backgroundColor: '#81c784' } },
                    { id: utilService.makeId(), title: 'Reusable bottle & eco straw set' },
                ],
            },
            {
                id: utilService.makeId(),
                title: 'Budget & Notes ',
                style: { backgroundColor: '#cfd8dc' },
                tasks: [
                    { id: utilService.makeId(), title: 'Total trip budget: ~3,500 USD' },
                    { id: utilService.makeId(), title: 'Accommodation average: $35/night' },
                    { id: utilService.makeId(), title: 'Daily expenses estimate: $40/day' },
                    { id: utilService.makeId(), title: 'Keep track of receipts via Splitwise', style: { backgroundColor: '#a5d6a7' } },
                    { id: utilService.makeId(), title: 'Set aside emergency fund: $200 cash' },
                ],
            },
        ],
    },

    // ===== 10 NAMED EMPTY DEMO BOARDS (#3–#12) =====
    {
        _id: utilService.makeId(),
        title: 'Italy Trip 🇮🇹',
        isStarred: false,
        createdAt: Date.now(),
        createdBy: {
            _id: 'u101',
            fullname: 'Eden Avgi',
            imgUrl: 'https://i.pravatar.cc/150?img=3',
        },
        style: { backgroundColor: '#f5b971' },
        labels: [],
        members: [],
        lists: [],
    },
    {
        _id: utilService.makeId(),
        title: 'Home Renovation 🏡',
        isStarred: false,
        createdAt: Date.now(),
        createdBy: {
            _id: 'u101',
            fullname: 'Eden Avgi',
            imgUrl: 'https://i.pravatar.cc/150?img=3',
        },
        style: { backgroundColor: '#cfd8dc' },
        labels: [],
        members: [],
        lists: [],
    },
    {
        _id: utilService.makeId(),
        title: 'Music Production 🎧',
        isStarred: false,
        createdAt: Date.now(),
        createdBy: {
            _id: 'u101',
            fullname: 'Eden Avgi',
            imgUrl: 'https://i.pravatar.cc/150?img=3',
        },
        style: { backgroundColor: '#cba6f7' },
        labels: [],
        members: [],
        lists: [],
    },
    {
        _id: utilService.makeId(),
        title: 'Design Portfolio 🎨',
        isStarred: false,
        createdAt: Date.now(),
        createdBy: {
            _id: 'u101',
            fullname: 'Eden Avgi',
            imgUrl: 'https://i.pravatar.cc/150?img=3',
        },
        style: { backgroundColor: '#f7d060' },
        labels: [],
        members: [],
        lists: [],
    },
    {
        _id: utilService.makeId(),
        title: 'Startup Ideas 🚀',
        isStarred: false,
        createdAt: Date.now(),
        createdBy: {
            _id: 'u101',
            fullname: 'Eden Avgi',
            imgUrl: 'https://i.pravatar.cc/150?img=3',
        },
        style: { backgroundColor: '#80cbc4' },
        labels: [],
        members: [],
        lists: [],
    },
    {
        _id: utilService.makeId(),
        title: 'Meal Planning 🍳',
        isStarred: false,
        createdAt: Date.now(),
        createdBy: {
            _id: 'u101',
            fullname: 'Eden Avgi',
            imgUrl: 'https://i.pravatar.cc/150?img=3',
        },
        style: { backgroundColor: '#ffcc80' },
        labels: [],
        members: [],
        lists: [],
    },
    {
        _id: utilService.makeId(),
        title: 'Fitness Goals 💪',
        isStarred: false,
        createdAt: Date.now(),
        createdBy: {
            _id: 'u101',
            fullname: 'Eden Avgi',
            imgUrl: 'https://i.pravatar.cc/150?img=3',
        },
        style: { backgroundColor: '#aed581' },
        labels: [],
        members: [],
        lists: [],
    },
    {
        _id: utilService.makeId(),
        title: 'Reading List 📚',
        isStarred: false,
        createdAt: Date.now(),
        createdBy: {
            _id: 'u101',
            fullname: 'Eden Avgi',
            imgUrl: 'https://i.pravatar.cc/150?img=3',
        },
        style: { backgroundColor: '#90caf9' },
        labels: [],
        members: [],
        lists: [],
    },
    {
        _id: utilService.makeId(),
        title: 'Photography Projects 📸',
        isStarred: false,
        createdAt: Date.now(),
        createdBy: {
            _id: 'u101',
            fullname: 'Eden Avgi',
            imgUrl: 'https://i.pravatar.cc/150?img=3',
        },
        style: { backgroundColor: '#f48fb1' },
        labels: [],
        members: [],
        lists: [],
    },
    {
        _id: utilService.makeId(),
        title: 'Shopping List 🛒',
        isStarred: false,
        createdAt: Date.now(),
        createdBy: {
            _id: 'u101',
            fullname: 'Eden Avgi',
            imgUrl: 'https://i.pravatar.cc/150?img=3',
        },
        style: { backgroundColor: '#d7ccc8' },
        labels: [],
        members: [],
        lists: [],
    },

]
